In [10]:
import numpy as np
a = ['Jerry','Tom','Lemon']
label = np.array([1,1,0])
label_list = label.tolist()
idx = -1
for text in a:
    idx = idx + 1
    if text == 'Lemon':
        a.remove(text)
        label_list.remove(label_list[idx])
label = np.array(label_list)
print(a)
print(label)

['Jerry', 'Tom']
[1 1]


In [9]:
for i in range(100,1000):
    hundred = i/100
    ten = (i-hundred*100) / 10
    one = i % 10
    if (i == hundred**2+ten**2+one**2):
        print(i)

In [2]:

import nltk.stem
from string import punctuation
s = nltk.stem.SnowballStemmer('english')
punct = punctuation

tokenized_list = [['imaging','hello',',','2020'],['looking','forward','to','seeing','you']]
tokens = []
for doc in tokenized_list:
    tokens.append([token.lower() for token in doc if token.lower() not in punct])
stemmed = []
for doc in tokens:
    stemmed.append([s.stem(token) for token in doc])
print(stemmed)





[['imag', 'hello', '2020'], ['look', 'forward', 'to', 'see', 'you']]


In [20]:
def getUnigram(words):
    """
        Input: a list of words, e.g., ['I', 'am', 'Denny']
        Output: a list of unigram
    """
    assert type(words) == list
    return words

def getBigram(words, join_string, skip=0):
    """
       Input: a list of words, e.g., ['I', 'am', 'Denny']
        Output: a list of bigram, e.g., ['I_am', 'am_Denny']
       I use _ as join_string for this example.
    """
    assert type(words) == list
    L = len(words)
        #print words
    if L > 1:
        lst = []
        for i in range(L-1):
            for k in range(1,skip+2):
                if i+k < L:
                    lst.append( join_string.join([words[i], words[i+k]]) )
    else:
        # set it as unigram
            lst = getUnigram(words)
        #print 'lst returned'
    return lst

def getTrigram(words, join_string, skip=0):
    """
       Input: a list of words, e.g., ['I', 'am', 'Denny']
       Output: a list of trigram, e.g., ['I_am_Denny']
       I use _ as join_string for this example.
    """
    assert type(words) == list
    L = len(words)
    if L > 2:
        lst = []
        for i in range(L-2):
            for k1 in range(1,skip+2):
                for k2 in range(1,skip+2):
                    if i+k1 < L and i+k1+k2 < L:
                        lst.append( join_string.join([words[i], words[i+k1], words[i+k1+k2]]) )
    else:
        # set it as bigram
        lst = getBigram(words, join_string, skip)
    return lst

join_str = "_"
unigram = []
unigram_corpus = []
bigram = []
bigram_corpus = []
trigram = []
trigram_corpus = []
for doc in stemmed:
    unigram.append(getUnigram(doc))
    unigram_corpus.extend(getUnigram(doc))
    bigram.append(getBigram(doc, join_str))
    bigram_corpus.extend(getBigram(doc, join_str))
    trigram.append(getTrigram(doc, join_str))
    trigram_corpus.extend(getTrigram(doc, join_str))

print(unigram)
print(unigram_corpus)
print(bigram)
print(bigram_corpus)
print(trigram)
print(trigram_corpus)

[['imag', 'hello', '2020'], ['look', 'forward', 'to', 'see', 'you']]
['imag', 'hello', '2020', 'look', 'forward', 'to', 'see', 'you']
[['imag_hello', 'hello_2020'], ['look_forward', 'forward_to', 'to_see', 'see_you']]
['imag_hello', 'hello_2020', 'look_forward', 'forward_to', 'to_see', 'see_you']
[['imag_hello_2020'], ['look_forward_to', 'forward_to_see', 'to_see_you']]
['imag_hello_2020', 'look_forward_to', 'forward_to_see', 'to_see_you']


In [ ]:
grams = ["unigram", "bigram", "trigram"]
for gram in grams:
        df["count_of_%s_%s" % (feat_name, gram)] = list(df.apply(lambda x: len(x[feat_name + "_" + gram]), axis=1))
        df["count_of_unique_%s_%s" % (feat_name, gram)] = \
        list(df.apply(lambda x: len(set(x[feat_name + "_" + gram])), axis=1))
        df["ratio_of_unique_%s_%s" % (feat_name, gram)] = \
        map(try_divide, df["count_of_unique_%s_%s"%(feat_name,gram)], df["count_of_%s_%s"%(feat_name,gram)])

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(unigram_corpus)
print(tfidf.shape)
vocabulary = vectorizer.vocabulary_

vecB = TfidfVectorizer(vocabulary=vocabulary)
tfidf = vecB.fit_transform(unigram)

words = vecB.get_feature_names()
print(words)
for i in range(len(unigram_corpus)):
    print('----Document %d----' % (i))
    for j in range(len(words)):
        if tfidf[i,j] > 1e-5:
              print( words[j], tfidf[i,j])


(8, 8)


D:\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1089: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


AttributeError: 'list' object has no attribute 'lower'

In [44]:
import numpy as np

list = [[1,2,3],[4,5,6]]

print(np.array(list).mean(axis=0))

[2.5 3.5 4.5]


In [52]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import numpy as np

sid = SentimentIntensityAnalyzer()
def compute_sentiment(sentences):
    result = []
    for sentence in sentences:
        vs = sid.polarity_scores(sentence)
        result.append(vs)
    
#    result_np = np.array(result).mean(axis=0)
#    result = result_np.tolist()
    return result

compute_sentiment(corpus)

[{'compound': 0.0, 'neg': 0.0, 'neu': 1.0, 'pos': 0.0},
 {'compound': 0.0, 'neg': 0.0, 'neu': 1.0, 'pos': 0.0},
 {'compound': 0.0, 'neg': 0.0, 'neu': 1.0, 'pos': 0.0},
 {'compound': 0.0, 'neg': 0.0, 'neu': 1.0, 'pos': 0.0}]

In [54]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import numpy as np

sentences = []
tricky_sentences = [
"Most automated sentiment analysis tools are shit.",
"VADER sentiment analysis is the shit.",
"Sentiment analysis has never been good.",
"Sentiment analysis with VADER has never been this good.",
"Warren Beatty has never been so entertaining.",
"I won't say that the movie is astounding and I wouldn't claim that \
the movie is too banal either.",
]
sentences.extend(tricky_sentences)
sid = SentimentIntensityAnalyzer()
for sentence in sentences:
    print(sentence)
    ss = sid.polarity_scores(sentence)
    print(ss)
    for k in sorted(ss):
        print('{0}: {1}, '.format(k, ss[k]), end='')

Most automated sentiment analysis tools are shit.
{'neg': 0.375, 'neu': 0.625, 'pos': 0.0, 'compound': -0.5574}
compound: -0.5574, neg: 0.375, neu: 0.625, pos: 0.0, VADER sentiment analysis is the shit.
{'neg': 0.0, 'neu': 0.556, 'pos': 0.444, 'compound': 0.6124}
compound: 0.6124, neg: 0.0, neu: 0.556, pos: 0.444, Sentiment analysis has never been good.
{'neg': 0.325, 'neu': 0.675, 'pos': 0.0, 'compound': -0.3412}
compound: -0.3412, neg: 0.325, neu: 0.675, pos: 0.0, Sentiment analysis with VADER has never been this good.
{'neg': 0.0, 'neu': 0.703, 'pos': 0.297, 'compound': 0.5228}
compound: 0.5228, neg: 0.0, neu: 0.703, pos: 0.297, Warren Beatty has never been so entertaining.
{'neg': 0.0, 'neu': 0.616, 'pos': 0.384, 'compound': 0.5777}
compound: 0.5777, neg: 0.0, neu: 0.616, pos: 0.384, I won't say that the movie is astounding and I wouldn't claim that the movie is too banal either.
{'neg': 0.0, 'neu': 0.851, 'pos': 0.149, 'compound': 0.4215}
compound: 0.4215, neg: 0.0, neu: 0.851, po

In [1]:
print ([0.]*300)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [1]:
list = [1,2,3,4]
list.remove(list[0])
print(list[0])

2


In [6]:
import nltk
nltk.stem.WordNetLemmatizer().lemmatize('looking')


'looking'

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('./data/fake_or_real_news.csv')
title=np.asarray(df.title)
text=np.asarray(df.text)
y=np.asarray(df.label)
title=[titles.lower().split() for titles in title]
text=[texts.lower().split() for texts in text]
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  \
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE   
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE   
2  U.S. Secretary of State John F. Kerry said Mon...  REAL   
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE   
4  It's primary day in New York and front-runners...  REAL   

                                       title_vectors  
0  [ 1.1533764e-02  4.2144405e-03  1.9692603e-02 ...  
1  [ 0.11267698  0.02518966 -0.00212591  0.021095...  
2  [ 0.04253004  0.04300297  0.01848392  0.048672...  
3  [ 0.10801624  0.11583211  0.02874823  0.061732...  
4  [ 1.69016439e-02  7.13498285e-03 -7.81233795e-...

In [4]:
import copy

titleandtext = []
for i in range(len(titleandtext)):
    titleandtext[i].extend(title[i])
    titleandtext[i].extend(text[i])

print(len(title[4526]))
print(len(text[4526]))
print(len(titleandtext[4526]))

15
1768


IndexError: list index out of range

In [2]:
import nltk
# Transform each review string as a list of token strings. May take a few seconds
text_token = [nltk.word_tokenize(text) for text in texts]

n = 0 #arbitrary pick
print('Example review:\n   Raw: {} \n\n   Tokenized: {}'.format(texts[n], [i for i in text_token[n]]))

Example review:
   Raw: Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. 
In the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. 
The word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. 
But that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. 
The FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. 
The FBI’s leadership is being war

In [4]:
from nltk.corpus import stopwords
from string import punctuation
from itertools import chain

def clean_text(tokenized_list, sw, punct, lemmatize=True):
    new_list = []
    for doc in tokenized_list:
        new_list.append([token.lower() for token in doc if token.lower() not in chain(punct, sw)])
    return new_list

# Remove punctuations and stopwords, and lower-case text
sw = stopwords.words('english')
punct = punctuation
text_cleaned = clean_text(text_token, sw, punct)

idx = -1
count = 0
label_list = labels.tolist()
for text in text_cleaned:
    idx = idx + 1
    if len(text) == 0:
        count = count + 1
        text_cleaned.remove(text)
        label_list.remove(label_list[idx])
        idx = idx - 1
labels = np.array(label_list)

print('how many texts are empty:',count)

how many texts are empty: 35


In [5]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from nltk.corpus import reuters

tokenized_docs = text_cleaned

print('tokenized_docs:\n',tokenized_docs[0])

# Convert tokenized documents to TaggedDocuments
tagged_docs = [TaggedDocument(doc, tags=[idx]) for idx, doc in enumerate(tokenized_docs)]

print('tagged_docs:\n',tagged_docs[0])

# Create and train the doc2vec model. May take a few seconds
doc2vec = Doc2Vec(size=300, window=5, min_count=5, dm = 1, iter=10)

# Build the word2vec model from the corpus
doc2vec.build_vocab(tagged_docs)

# Train the models
doc2vec.train(tagged_docs, epochs=10, total_examples=doc2vec.corpus_count)

D:\Anaconda3\lib\site-packages\gensim\utils.py:1209: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
D:\Anaconda3\lib\site-packages\gensim\models\doc2vec.py:531: UserWarning: The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.
  warnings.warn("The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.")


tokenized_docs:
 ['daniel', 'greenfield', 'shillman', 'journalism', 'fellow', 'freedom', 'center', 'new', 'york', 'writer', 'focusing', 'radical', 'islam', 'final', 'stretch', 'election', 'hillary', 'rodham', 'clinton', 'gone', 'war', 'fbi', 'word', '“', 'unprecedented', '”', 'thrown', 'around', 'often', 'election', 'ought', 'retired', '’', 'still', 'unprecedented', 'nominee', 'major', 'political', 'party', 'go', 'war', 'fbi', '’', 'exactly', 'hillary', 'people', 'done', 'coma', 'patients', 'waking', 'watching', 'hour', 'cnn', 'hospital', 'beds', 'would', 'assume', 'fbi', 'director', 'james', 'comey', 'hillary', '’', 'opponent', 'election', 'fbi', 'attack', 'everyone', 'obama', 'cnn', 'hillary', '’', 'people', 'circulated', 'letter', 'attacking', 'comey', 'currently', 'media', 'hit', 'pieces', 'lambasting', 'targeting', 'trump', '’', 'surprising', 'clintons', 'allies', 'start', 'running', 'attack', 'ads', 'fbi', 'fbi', '’', 'leadership', 'warned', 'entire', 'left-wing', 'establishment'

D:\Anaconda3\lib\site-packages\gensim\models\doc2vec.py:535: UserWarning: The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.
  warnings.warn("The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.")


In [6]:
doc2vec_data = np.zeros((len(text_cleaned),300))
for i in range (len(text_cleaned)):
    doc2vec_data[i] = doc2vec.infer_vector(text_cleaned[i])

print(doc2vec_data[0])

[-0.61935633  1.31671917  0.86740804 -0.1553306   0.15756744  0.43971166
  0.25862303 -0.08088062  0.91815299 -0.11218839 -0.6973688   0.37162742
  0.30071414  0.59860969  0.39462444  0.63498664 -0.41228274 -0.81001973
 -0.45109209  0.06411766 -0.58660787 -0.19415447  0.23305048  0.46412504
 -0.15703677  1.0946511  -0.9181062   0.12459357 -0.0564952  -0.10358798
  0.48112518  0.22236991 -0.24725345  0.16025317  1.18726146  0.53739101
 -0.19515121 -0.13357428 -0.51477522 -0.80267876  0.26043892 -0.28965446
  0.17460492 -0.84917319  1.16470981  0.30701593  0.4209992  -0.49751049
 -1.13366485 -0.19177148 -0.04489039  0.20668036 -1.20697701 -0.38073269
  0.3211171  -1.01165211 -0.03382358  0.13255063  0.12060357 -0.17878529
 -0.3298957  -0.79989678 -0.20509571  0.34377712  0.06300732  0.4184415
 -0.04797495 -0.04306135 -0.12024839 -0.5250262   0.13047108  0.37586787
 -0.55637836  0.3299264  -0.2715697  -0.138197   -0.71471792 -0.09325261
  0.29613003  0.38286316 -0.67791384 -0.04511396 -0.

In [7]:
from sklearn.model_selection import train_test_split

# split data into train and test sets
seed = 42
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(doc2vec_data, labels, test_size=test_size, random_state=seed)
print(X_test.shape)

(2079, 300)


In [8]:
# instantiate a SVM regression model, and fit with X and y
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score


model = LogisticRegression()
model = model.fit(X_train, y_train.astype(int))

y_pred = model.predict(X_test)

print(y_pred[0:10])
# check the accuracy on the training set
print(confusion_matrix(y_true=y_test.astype(int), y_pred=y_pred))
score = model.score(X_test, y_test.astype(int))

p = precision_score(y_test.astype(int), y_pred, average='binary')
r = recall_score(y_test.astype(int), y_pred, average='binary')
f1score = f1_score(y_test.astype(int), y_pred, average='binary')
print('accuracy:',score)
print('precision:',p)
print('recall:',r)
print('f1score:',f1score)

[0 1 0 0 1 1 1 1 1 0]
[[502 519]
 [527 531]]
accuracy: 0.49687349687349686
precision: 0.5057142857142857
recall: 0.501890359168242
f1score: 0.5037950664136623


In [3]:
title = ['1']
text = ['1','2','3']
for title,text in zip(title,text):
    print(title,text)

1 1


In [4]:
import numpy as np


x = np.random.randn(10)
print(x)

[-1.14641257 -0.98182771  1.92635137 -2.04952002  0.00528416 -0.40082222
 -0.72675502 -0.61174331 -0.70071689  0.52017262]


In [9]:
import numpy as np
x = np.nan
print(x*1)

nan


In [5]:
title = ['text','svsdfs','sdfsdg']
text= ['title','gdsfgsdfg','ghjhgjghd']

title.extend(text)
print(title)

['text', 'svsdfs', 'sdfsdg', 'title', 'gdsfgsdfg', 'ghjhgjghd']


In [7]:
import numpy as np
a = np.array([2,3,4])
a = a*4
print(a)

[ 8 12 16]


In [1]:
x = [(i*20,)*i  for i in range(1,5) ]
print(x)

[(20,), (40, 40), (60, 60, 60), (80, 80, 80, 80)]


In [9]:
import numpy as np

hidden_layer_size = []
for i in np.linspace(200,300,5):
    for j in np.linspace(50,100,6):
        for k in np.linspace(5,10,2):
            hidden_layer_size.append((i,j,k))
print(hidden_layer_size)
    

[(200.0, 50.0, 5.0), (200.0, 50.0, 10.0), (200.0, 60.0, 5.0), (200.0, 60.0, 10.0), (200.0, 70.0, 5.0), (200.0, 70.0, 10.0), (200.0, 80.0, 5.0), (200.0, 80.0, 10.0), (200.0, 90.0, 5.0), (200.0, 90.0, 10.0), (200.0, 100.0, 5.0), (200.0, 100.0, 10.0), (225.0, 50.0, 5.0), (225.0, 50.0, 10.0), (225.0, 60.0, 5.0), (225.0, 60.0, 10.0), (225.0, 70.0, 5.0), (225.0, 70.0, 10.0), (225.0, 80.0, 5.0), (225.0, 80.0, 10.0), (225.0, 90.0, 5.0), (225.0, 90.0, 10.0), (225.0, 100.0, 5.0), (225.0, 100.0, 10.0), (250.0, 50.0, 5.0), (250.0, 50.0, 10.0), (250.0, 60.0, 5.0), (250.0, 60.0, 10.0), (250.0, 70.0, 5.0), (250.0, 70.0, 10.0), (250.0, 80.0, 5.0), (250.0, 80.0, 10.0), (250.0, 90.0, 5.0), (250.0, 90.0, 10.0), (250.0, 100.0, 5.0), (250.0, 100.0, 10.0), (275.0, 50.0, 5.0), (275.0, 50.0, 10.0), (275.0, 60.0, 5.0), (275.0, 60.0, 10.0), (275.0, 70.0, 5.0), (275.0, 70.0, 10.0), (275.0, 80.0, 5.0), (275.0, 80.0, 10.0), (275.0, 90.0, 5.0), (275.0, 90.0, 10.0), (275.0, 100.0, 5.0), (275.0, 100.0, 10.0), (300.0,